config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'stations#index'

  resources :stations

  namespace :api, constraints: { format: 'json' } do
    resources :stations, only: [] do
      resources :sensors, only: :index
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/station.rb
# frozen_string_literal: true

class Station < ApplicationRecord
  validates :name, :public_id, presence: true
end

app/controllers/api/sensors_controller.rb
# frozen_string_literal: true

module Api
  class SensorsController < ApplicationController
    before_action :set_station

    def index
      @sensors = PjpApi::Sensor.find_all_by_station(@station.public_id)
    end

    private

    def set_station
      @station = Station.find(params[:station_id])
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/stations_controller.rb
# frozen_string_literal: true

class StationsController < ApplicationController
  before_action :set_station, only: %i[show destroy]

  def index
    @stations = Station.order(created_at: :asc)
  end

  def new
    @stations = PjpApi::Station.all
  end

  def create
    result = CreateStation.call(public_id: station_public_id)

    if result.success?
      redirect_to stations_path, notice: 'The station has been saved'
    else
      render :new
    end
  end

  def show; end

  def destroy
    @station.destroy
    redirect_to stations_path, notice: 'The station has been removed'
  end

  private

  def set_station
    @station = Station.find(params[:id])
  end

  def station_public_id
    params['station_public_id']
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Smog
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .panel.panel-default.col-md-10.col-md-offset-1.main-container
      .panel-body
        - if alert
          .alert.alert-danger= alert

        - if notice
          .alert.alert-success= notice

        = yield

app/views/stations/index.haml
.page-header
  %h1
    Stations
    .pull-right= link_to 'Add New', new_station_path, class: 'btn btn-primary'

%table.table
  %thead
    %tr
      %th #
      %th Name
      %th Created at
      %th Updated at
      %th Actions

  %tbody
    - @stations.to_enum.with_index(1).each do |station, i|
      %tr
        %td= i
        %td= station.name
        %td= station.created_at.strftime('%c')
        %td= station.updated_at.strftime('%c')
        %td
          = link_to 'Show', station_path(station)
          = link_to 'Destroy', station_path(station), method: :delete, data: { confirm: 'Are you sure?' }

app/views/stations/new.haml
.page-header
  %h1 Add new station

= form_with url: stations_path do |f|
  - @stations.each do |station|
    .radio
      %label
        = f.radio_button :station_public_id, station.id
        = station.name

  = f.submit 'Add', class: 'btn btn-primary'

app/views/stations/show.haml
.page-header
  %h1
    Station:
    = @station.name

#app-container